# Generated by Django 5.2.10 on 2026-01-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., S4A, P7 Blue, Form 5 Science', max_length=100, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('teacher_name', models.CharField(blank=True, max_length=150)),
                ('academic_year', models.CharField(default='2025/2026', max_length=9)),
            ],
            options={
                'verbose_name': 'Class / Grade Group',
                'verbose_name_plural': 'Classes / Grade Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student registration/ID number (e.g., KHS/2025/001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', help_text="Student's gender", max_length=1)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Passport-size photo', null=True, upload_to='student_photos/')),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active / currently enrolled')),
                ('class_group', models.ForeignKey(blank=True, help_text='The class/grade group the student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.classgroup')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
