# Generated by Django 5.2.10 on 2026-01-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='schools.school', verbose_name='School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='schools.school', verbose_name='School'),
            preserve_default=False,
        ),
    ]
