# Generated by Django 5.2.10 on 2026-01-22 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_school_category_school'),
        ('students', '0002_classgroup_school_student_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Date Returned')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('OVERDUE', 'Overdue'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20, verbose_name='Status')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Fine (UGX)')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='Fine Paid?')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='books.book', verbose_name='Book')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='students.student', verbose_name='Borrower')),
            ],
            options={
                'verbose_name': 'Borrow Transaction',
                'verbose_name_plural': 'Borrow Transactions',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='transaction_student_b2fd54_idx'), models.Index(fields=['book', 'status'], name='transaction_book_id_3c2609_idx'), models.Index(fields=['due_date'], name='transaction_due_dat_8232be_idx')],
            },
        ),
    ]
