# Generated by Django 5.2.10 on 2026-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='fine_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid (UGX)'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='max_renewals',
            field=models.PositiveIntegerField(default=2, verbose_name='Max Renewals Allowed'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Renewal Count'),
        ),
    ]
