# Generated by Django 5.2.10 on 2026-01-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_borrowtransaction_fine_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='fine_paid_amount',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='max_renewals',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='renewal_count',
        ),
    ]
