# Generated by Django 5.2.10 on 2026-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_borrowtransaction_fine_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='max_renewals',
            field=models.PositiveIntegerField(default=2, verbose_name='Max Renewals Allowed'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Renewal Count'),
        ),
    ]
